name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make libsdl2-dev libsdl2-ttf-dev doxygen graphviz

      - name: Configure (tests)
        run: cmake -B build-tests -S . -DBUILD_TESTS=ON -DBUILD_FIRMWARE=OFF -DBUILD_SIM=OFF

      - name: Build (tests)
        run: cmake --build build-tests -j

      - name: Run tests
        run: ctest --test-dir build-tests --output-on-failure

      - name: Configure (simulator)
        run: cmake -B build-sim -S . -DBUILD_SIM=ON -DBUILD_TESTS=OFF -DBUILD_FIRMWARE=OFF

      - name: Build (simulator)
        run: cmake --build build-sim -j

      - name: Generate Doxygen docs
        run: doxygen Doxyfile || true

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs/
          if-no-files-found: warn
